<a href="https://colab.research.google.com/github/doniaskima/Deep-learning-with-tensorflow/blob/master/Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf ;

In [11]:
tensor_indexed = tf.constant([3,6,3,2,13,43,54])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[1:5+1])
print(tensor_indexed[1:6])
print(tensor_indexed[:4])
print(tensor_indexed[3:-3])


tf.Tensor([ 3  6  3  2 13 43 54], shape=(7,), dtype=int32)
tf.Tensor([3 6 3 2], shape=(4,), dtype=int32)
tf.Tensor([ 6  3  2 13 43], shape=(5,), dtype=int32)
tf.Tensor([ 6  3  2 13 43], shape=(5,), dtype=int32)
tf.Tensor([3 6 3 2], shape=(4,), dtype=int32)
tf.Tensor([2], shape=(1,), dtype=int32)


In [8]:
tf.range(2,6)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>

In [19]:
# Create a TensorFlow tensor with the specified values.
tensor_two_d = tf.constant([[1, 2, 0],
                             [3, 5, -1],
                             [13, 35, -1],
                             [2, 3, 8]])

# The [] operators are used to index the tensor. The first index specifies the row and the second index specifies the column.
# Select the first three rows and the first two columns of the tensor.
tensor_slice = tensor_two_d[0:3, 0:2]

# Print the value of the tensor slice to the console.
print(tensor_slice)
print(tensor_two_d[2,:])
print(tensor_two_d[2,1:])
print(tensor_two_d[1:3,0])
print(tensor_two_d[...,1])



tf.Tensor(
[[ 1  2]
 [ 3  5]
 [13 35]], shape=(3, 2), dtype=int32)
tf.Tensor([13 35 -1], shape=(3,), dtype=int32)
tf.Tensor([35 -1], shape=(2,), dtype=int32)
tf.Tensor([ 3 13], shape=(2,), dtype=int32)
tf.Tensor([ 2  5 35  3], shape=(4,), dtype=int32)


In [32]:
# Create a three-dimensional TensorFlow tensor with the specified values.
tensor_three_d = tf.constant([[[1,2,0],
                                 [3,2,-1]],
                                [[1,2,0],
                                 [9,4,1]],
                                [[1,2,0],
                                 [3,5,-1]],
                                [[1,2,0],
                                 [9,12,99]]])

# Print the first slice of the tensor.
print(tensor_three_d[0, :, :])

# Print the first element of the tensor.
print(tensor_three_d[0, 0, :])

# Print the last column of the first two slices of the tensor.
print(tensor_three_d[0:2, :, 2])

# Print the last column of all slices of the tensor.
print(tensor_three_d[0:2, ..., 2])


tf.Tensor(
[[ 1  2  0]
 [ 3  2 -1]], shape=(2, 3), dtype=int32)
tf.Tensor([1 2 0], shape=(3,), dtype=int32)
tf.Tensor(
[[ 0 -1]
 [ 0  1]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 0 -1]
 [ 0  1]], shape=(2, 2), dtype=int32)
