<a href="https://colab.research.google.com/github/doniaskima/Deep-learning-with-tensorflow/blob/master/3_Maths_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf ;

In [3]:
x_abs = tf.constant([2,-23,12,-21])
tf.abs(x_abs)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 2, 23, 12, 21], dtype=int32)>

In [5]:
x_abs_complex = tf.constant([-2.25+4.76j])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.26498813])>

In [6]:
tf.sqrt(-2.25**2+4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=4.1833>

In [18]:
import tensorflow as tf

x_1 = tf.constant([[2,-23,12,-21],[22,-3,2,1]], dtype=tf.float32)
x_2 = tf.constant([82,-3,2,1], dtype=tf.int32)

# Cast the `x_2` tensor to the same data type as the `x_1` tensor.
x_2_casted = tf.cast(x_2, dtype=tf.float32)

# Perform arithmetic operations on the `x_1` and `x_2_casted` tensors.
print(tf.add(x_1, x_2_casted))
print(tf.multiply(x_1, x_2_casted))
print(tf.subtract(x_1, x_2_casted))
print(tf.divide(x_1, x_2_casted))
print(x_1.shape)


tf.Tensor(
[[ 84. -26.  14. -20.]
 [104.  -6.   4.   2.]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 1.640e+02  6.900e+01  2.400e+01 -2.100e+01]
 [ 1.804e+03  9.000e+00  4.000e+00  1.000e+00]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-80. -20.  10. -22.]
 [-60.   0.   0.   0.]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[  0.02439024   7.6666665    6.         -21.        ]
 [  0.2682927    1.           1.           1.        ]], shape=(2, 4), dtype=float32)
(2, 4)


In [20]:
x_argmax = tf.constant([[-2,20,-30,6,3],[9,20,30,16,13],[22,20,30,36,78]])
print(x_argmax.shape)

(3, 5)


In [26]:
import tensorflow as tf

# Create a TensorFlow tensor with the values [[2, 20, 30, 3, 6]].
x_argmax = tf.constant([[2, 20, 30, 3, 6]])

# Flatten the tensor.
x_argmax_flat = tf.reshape(x_argmax, [-1])

# Find the index of the largest element in the flattened tensor.
argmax = tf.argmax(x_argmax_flat)

# Print the value of the argmax tensor.
print(argmax)


tf.Tensor(2, shape=(), dtype=int64)


In [34]:
# Create a TensorFlow tensor with the values [[2, 20, 30, 3, 6]].
x_argmax = tf.constant([[2, 20, 30, 3, 6],
                        [-62, 20, 0, -3, 6],
                        [5, 24, 3, 3, 6],
                        [9, 2, 30, 3, 16]])

# Find the index of the largest element in the tensor along the axis 0.
# The axis 0 argument specifies that we want to find the index of the largest element in each row.
argmax = tf.math.argmax(x_argmax, axis=1)
# Find the index of the smallest element in the tensor along the axis 0.
# The axis 0 argument specifies that we want to find the index of the smallest element in each row.
argmin = tf.math.argmin(x_argmax, axis=0)

# Print the value of the argmax and argmin tensors.
print(argmax)
print(argmin)


tf.Tensor([2 1 1 2], shape=(4,), dtype=int64)
tf.Tensor([1 3 1 1 0], shape=(5,), dtype=int64)


In [35]:
x= tf.constant([[2,2],[3,3]])
y = tf.constant([[5,1],[4,9]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[   32,     2],
       [   81, 19683]], dtype=int32)>

In [36]:
tf.pow(tf.constant(2),tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [42]:
tensor_two_d =tf.constant([[1,2,0],
                           [3,5,-1],
                           [1,5,6],
                           [3,5,1]])
print(tf.math.reduce_max(tensor_two_d,axis=None,keepdims=False,name=None))
print(tf.math.reduce_sum(tensor_two_d,axis=0,keepdims=True,name=None))


tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor([[ 8 17  6]], shape=(1, 3), dtype=int32)


In [40]:
7/4

1.75