<a href="https://colab.research.google.com/github/doniaskima/Deep-learning-with-tensorflow/blob/master/4_Linear_algebra_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf


In [7]:
# Create two TensorFlow constants, x_1 and x_2.
x_1 = tf.constant([[11,52,0],
                   [3,5,-1],
                   [32,3,-3]])

x_2 = tf.constant([[1,2,0],
                   [3,5,-1],
                   [32,3,-3]])

x_3 = tf.constant([[1,2,0],
                   [-23,35,1],
                   [32,83,-3]])

# Perform matrix multiplication on x_1 and x_2.
# The transpose_a and transpose_b flags specify whether to transpose the matrices before multiplying them.
# The adjoint_a and adjoint_b flags specify whether to take the adjoint of the matrices before multiplying them.
# The a_is_sparse and b_is_sparse flags specify whether the matrices are sparse matrices.
# The output_type flag specifies the data type of the output matrix.
# The name flag specifies the name of the operation.
matmul = tf.linalg.matmul(
    x_1,
    x_2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)
print(matmul)
print(tf.transpose(matmul));
print(matmul.shape)
print(x_1@x_2)
print(x_3@tf.transpose(x_2))
print(tf.transpose(x_1))

tf.Tensor(
[[167 282 -52]
 [-14  28  -2]
 [-55  70   6]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[167 -14 -55]
 [282  28  70]
 [-52  -2   6]], shape=(3, 3), dtype=int32)
(3, 3)
tf.Tensor(
[[167 282 -52]
 [-14  28  -2]
 [-55  70   6]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[   5   13   38]
 [  47  105 -634]
 [ 198  514 1282]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[11  3 32]
 [52  5  3]
 [ 0 -1 -3]], shape=(3, 3), dtype=int32)


In [8]:
import tensorflow as tf

# Define the tensors
tensor_two_d_n = tf.constant([[0, -1, -2], [1, 0, -1], [2, 1, 0], [3, 2, 1]], dtype=tf.float16)
tensor_two_d_n_ = tf.constant([[0, 1, 2], [-1, 0, 1], [-2, -1, 0], [-3, -2, -1]], dtype=tensor_two_d_n.dtype)

# Define the variables
m = 1
n = 0

# Print the tensors and variables
print(tensor_two_d_n)
print(tensor_two_d_n_)
print(m)
print(n)


tf.Tensor(
[[ 0. -1. -2.]
 [ 1.  0. -1.]
 [ 2.  1.  0.]
 [ 3.  2.  1.]], shape=(4, 3), dtype=float16)
tf.Tensor(
[[ 0.  1.  2.]
 [-1.  0.  1.]
 [-2. -1.  0.]
 [-3. -2. -1.]], shape=(4, 3), dtype=float16)
1
0


In [16]:
# Create the input matrix
tensor_two_d_n = tf.constant([[0, -1, -2], [1, 0, -1], [2, 1, 0], [3, 2, 1]], dtype=tf.float16)

# Extract the lower triangular part of the matrix
tensor_two_d_n_lower_triangular = tf.linalg.band_part(tensor_two_d_n, -1, 0)

# Print the lower triangular part of the matrix
print(tensor_two_d_n_lower_triangular)


tf.Tensor(
[[0. 0. 0.]
 [1. 0. 0.]
 [2. 1. 0.]
 [3. 2. 1.]], shape=(4, 3), dtype=float16)


In [19]:
#  Matrix Inversion:


# Define a square matrix
matrix = tf.constant([[1.0, 2.0], [3.0, 4.0]], dtype=tf.float32)

# Invert the matrix
inverted_matrix = tf.linalg.inv(matrix)
print(inverted_matrix)



tf.Tensor(
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]], shape=(2, 2), dtype=float32)


In [27]:
import tensorflow as tf

# Define a matrix
matrix = tf.constant([[1.0, 2.0], [3.0, 4.0]], dtype=tf.float32)

# Perform SVD
s, u, v = tf.linalg.svd(matrix)

# Print the singular values
print(s)

# Print the left singular vectors
print(u)

# Print the right singular vectors
print(v)


tf.Tensor([5.4649854  0.36596614], shape=(2,), dtype=float32)
tf.Tensor(
[[ 0.4045535 -0.9145143]
 [ 0.9145143  0.4045535]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.5760484  0.8174156]
 [ 0.8174156 -0.5760484]], shape=(2, 2), dtype=float32)


In [23]:
# Eigenvalue and Eigenvector Calculation:

# Define a matrix
matrix = tf.constant([[1.0, 2.0], [2.0, 1.0]], dtype=tf.float32)

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = tf.linalg.eig(matrix)

print(eigenvalues)
print(eigenvectors)


tf.Tensor([ 2.9999998 +0.j -0.99999994+0.j], shape=(2,), dtype=complex64)
tf.Tensor(
[[ 0.7071068+0.j -0.7071068+0.j]
 [ 0.7071068+0.j  0.7071068+0.j]], shape=(2, 2), dtype=complex64)


In [24]:
# Matrix Determinant:

# Define a square matrix
matrix = tf.constant([[1.0, 2.0], [3.0, 4.0]], dtype=tf.float32)

# Compute the determinant
determinant = tf.linalg.det(matrix)


In [26]:
# Define a square matrix
matrix = tf.constant([[1.0, 2.0], [3.0, 4.0]], dtype=tf.float32)

# Compute the determinant
determinant = tf.linalg.det(matrix)
print(determinant)


tf.Tensor(-2.0, shape=(), dtype=float32)
