<a href="https://colab.research.google.com/github/doniaskima/Deep-learning-with-tensorflow/blob/master/4_Linear_algebra_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf


In [12]:
# Create two TensorFlow constants, x_1 and x_2.
x_1 = tf.constant([[1,2,0],
                   [3,5,-1],
                   [32,3,-3]])
x_2 = tf.constant([[1,2,0],
                   [3,5,-1],
                   [32,3,-3]])

# Perform matrix multiplication on x_1 and x_2.
# The transpose_a and transpose_b flags specify whether to transpose the matrices before multiplying them.
# The adjoint_a and adjoint_b flags specify whether to take the adjoint of the matrices before multiplying them.
# The a_is_sparse and b_is_sparse flags specify whether the matrices are sparse matrices.
# The output_type flag specifies the data type of the output matrix.
# The name flag specifies the name of the operation.
matmul = tf.linalg.matmul(
    x_1,
    x_2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)
print(matmul)
print(matmul.shape)
print(x_1@x_2)

tf.Tensor(
[[  7  12  -2]
 [-14  28  -2]
 [-55  70   6]], shape=(3, 3), dtype=int32)
(3, 3)
tf.Tensor(
[[  7  12  -2]
 [-14  28  -2]
 [-55  70   6]], shape=(3, 3), dtype=int32)


In [13]:
tf.transpose(x_1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  3, 32],
       [ 2,  5,  3],
       [ 0, -1, -3]], dtype=int32)>