<a href="https://colab.research.google.com/github/doniaskima/Deep-learning-with-tensorflow/blob/master/5_Common_TensorFlow_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#  Creating Tensors:

import tensorflow as tf

# Create a constant tensor
tensor_a = tf.constant([1, 2, 3], dtype=tf.float32)

# Create a variable tensor (trainable)
tensor_b = tf.Variable([4, 5, 6], dtype=tf.float32)



In [4]:
# Math Operations:

a = tf.constant(2, dtype=tf.float32)
b = tf.constant(3, dtype=tf.float32)

# Addition
c = tf.add(a, b)

# Subtraction
d = tf.subtract(a, b)

# Multiplication
e = tf.multiply(a, b)

# Division
f = tf.divide(a, b)



In [5]:
# Activation Functions:


x = tf.constant([-2, -1, 0, 1, 2], dtype=tf.float32)

# ReLU activation
relu_output = tf.nn.relu(x)



In [6]:
# Loss Functions:

# Define the predicted and true values
y_pred = tf.constant([1.0, 2.0, 3.0], dtype=tf.float32)
y_true = tf.constant([0.5, 2.5, 3.5], dtype=tf.float32)

# Compute Mean Squared Error
mse = tf.losses.mean_squared_error(y_true, y_pred)

In [11]:
import tensorflow as tf

x = tf.constant([[[2,1,2,1,4,5]]])

# Add a dimension to the tensor x
x = tf.expand_dims(x, axis=0)

# Print the shape of the expanded tensor
print(x.shape)


(1, 1, 1, 6)


In [16]:
import tensorflow as tf

x = tf.constant([[[2,1,2,1,4,5]]])

# Squeeze the tensor x along the axis 0
x_squeezed = tf.squeeze(x, axis=0)

# Check if the squeezed tensor has any dimensions of size 1
while tf.reduce_any(tf.shape(x_squeezed) == 1):
  # Squeeze the squeezed tensor again
  x_squeezed = tf.squeeze(x_squeezed, axis=0)

# Print the shape of the squeezed tensor
print(x_squeezed.shape)


(6,)


In [1]:
import tensorflow as tf

# Create two matrices
matrix_1 = tf.constant([[1, 2, 3], [4, 5, 6]])
matrix_2 = tf.constant([[7, 8, 9], [10, 11, 12]])

# Concatenate the two matrices along the first dimension
concatenated_matrix_1 = tf.concat([matrix_1, matrix_2], axis=0)

# Concatenate the two matrices along the second dimension
concatenated_matrix_2 = tf.concat([matrix_1, matrix_2], axis=1)

# Print the concatenated matrices
print(concatenated_matrix_1)
print(concatenated_matrix_2)


tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


In [2]:
import tensorflow as tf

# Create a list of tensors
t1 = tf.constant([1, 2, 3])
t2 = tf.constant([4, 5, 6])
t3 = tf.constant([7, 8, 9])

# Stack the tensors along the first dimension
stacked_tensors = tf.stack([t1, t2, t3])

# Print the stacked tensors
print(stacked_tensors)


tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [5]:
import tensorflow as tf

# Create a tensor
t = tf.constant([1, 2, 3, 4, 5, 6])

# Reshape the tensor to have a shape of (2, 3)
t_reshaped = tf.reshape(t, [2, 3])

# Print the reshaped tensor
print(t_reshaped)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [6]:
import tensorflow as tf

# Create two tensors
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.constant([[7, 8, 9], [10, 11, 12]])

# Reshape t2 to have the same rank as t1_expanded
t2_reshaped = tf.reshape(t2, [2, 1, 3])
print(t2_reshaped)

# Concatenate the two tensors along the second dimension
concatenated_tensors = tf.concat([t1_expanded, t2_reshaped], axis=1)

# Print the concatenated tensors
print(concatenated_tensors)


tf.Tensor(
[[[ 7  8  9]]

 [[10 11 12]]], shape=(2, 1, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [7]:
import tensorflow as tf

# Create a tensor
t = tf.constant([[1, 2, 3], [4, 5, 6]])

# Pad the tensor with zeros along the top and bottom
padded_t = tf.pad(t, [[1, 1], [0, 0]], constant_values=0)

# Print the padded tensor
print(padded_t)


tf.Tensor(
[[0 0 0]
 [1 2 3]
 [4 5 6]
 [0 0 0]], shape=(4, 3), dtype=int32)


In [10]:
import tensorflow as tf

# Create a tensor
t = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create a list of indices
indices = [0, 2, 4]

# Clip the indices to the range of the tensor
clipped_indices = tf.clip_by_value(indices, 0, tf.shape(t)[0] - 1)

# Gather the elements at the clipped indices
gathered_t = tf.gather(t, clipped_indices, axis=0)

# Print the gathered tensor
print(gathered_t)


tf.Tensor(
[[1 2 3]
 [7 8 9]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [1]:
import tensorflow as tf

# Create a tensor
t = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create a list of indices
indices = [[0, 2], [1, 1]]

# Gather the elements at the indices
gathered_t = tf.gather_nd(t, indices)

# Print the gathered tensor
print(gathered_t)


tf.Tensor([3 5], shape=(2,), dtype=int32)


In [4]:
indices=[[2,1]]
params=[['a','b'],
        ['c','d'],
        ['e','f']]
tf.gather_nd(params,indices);
print(params)

[['a', 'b'], ['c', 'd'], ['e', 'f']]


In [8]:
tensor_two_d=[[1,2,0,],
              [3,],
              [1,3,2,5,5,6],
              [2,3]]
tensor_ragged=tf.ragged.constant(tensor_two_d)
print(tensor_ragged)

<tf.RaggedTensor [[1, 2, 0], [3], [1, 3, 2, 5, 5, 6], [2, 3]]>


In [10]:
import tensorflow as tf

# Create a ragged tensor
tensor_two_d=[[1, 2, 3], [4, 5], []]
tensor_ragged=tf.ragged.constant(tensor_two_d)

# Remove the third row from the ragged tensor
tensor_ragged = tensor_ragged[:-1]

# Print the ragged tensor
print(tensor_ragged)


<tf.RaggedTensor [[1, 2, 3], [4, 5]]>


In [11]:
# Create a sparse tensor
sparse_tensor = tf.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 3], dense_shape=[3, 4])

# Print the sparse tensor
print(sparse_tensor)


SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 3], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [13]:
tf.sparse.to_dense(sparse_tensor)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 0]], dtype=int32)>

In [14]:
import tensorflow as tf

# Create a string tensor
string_tensor = tf.constant(["Hello, TensorFlow!", "This is a string tensor."])

# Print the string tensor
print(string_tensor)


tf.Tensor([b'Hello, TensorFlow!' b'This is a string tensor.'], shape=(2,), dtype=string)


In [15]:
import tensorflow as tf

# Create a list of strings
split_strings = ["Hello", "TensorFlow!"]

# Join the list of strings into a single string
joined_string = tf.strings.join(split_strings, separator=", ")

# Print the joined string
print(joined_string)


tf.Tensor(b'Hello, TensorFlow!', shape=(), dtype=string)
