<a href="https://colab.research.google.com/github/doniaskima/Deep-learning-with-tensorflow/blob/master/Neuralearn_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import tensorflow as tf ;

In [14]:
tensor_zero_d = tf.constant(4);
print(tensor_zero_d);

tf.Tensor(4, shape=(), dtype=int32)


In [15]:
tensor_one_d = tf.constant([2,0,-3]);
print(tensor_one_d);

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [16]:
tensor_two_d = tf.constant([
    [2,0,-3],
    [3,5,1],
    [2,0,-3],
    [3,5,1]
]);
print(tensor_two_d);

tf.Tensor(
[[ 2  0 -3]
 [ 3  5  1]
 [ 2  0 -3]
 [ 3  5  1]], shape=(4, 3), dtype=int32)


In [17]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=3,
    dtype=tf.dtypes.float32,
    name=None,
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [18]:
fill_tensor = tf.fill(
    [1,2,3],5,None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5]
  [5 5 5]]], shape=(1, 2, 3), dtype=int32)


In [19]:
random_tensor = tf.random.normal(
    [3,2],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None,
)
print(random_tensor)

tf.Tensor(
[[-0.07211637  1.8592203 ]
 [-1.7341077   0.3984149 ]
 [-0.38601193  1.5541536 ]], shape=(3, 2), dtype=float32)


In [20]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)


tf.Tensor(
[[[1 1 1]
  [1 1 1]]], shape=(1, 2, 3), dtype=int32)
